### ISSUE TITLE
Lock down s3 bucket permission/access

### ISSUE THREAD

**Issue by stefanfranzen** [weaddquality/business-model-canvas#20]
- [x] S3 bucket is set to public access (da0e44f)

**Comment by mansn** [comment]
AWS CloudFront is one solution, not sure if it's the easiest one, [but S3 + CloudFront seems to be a nice match](https://aws.amazon.com/blogs/networking-and-content-delivery/amazon-s3-amazon-cloudfront-a-match-made-in-the-cloud/).

**Comment by mansn** [comment]
Done. S3 bucket is now locked down, and we now access the application through CloudFront instead. 

The README has been updated with the latest url (da0e44f).
